# Default values for onepassword-events.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

role_id:
secret_id:
secret_path:

image:
  repository:  core.harbor.equityzen.com/development/onepassword
  pullPolicy: Always
  pullSecret: harborimagekey
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.5"


serviceAccount:
  name: vaultsa

podAnnotations: {}


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi


nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: kops.k8s.io/instancegroup
              operator: In
              values:
                - nodes
