apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onepassword-events.fullname" . }}
  labels:
    {{- include "onepassword-events.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "onepassword-events.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "onepassword-events.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: harborimagekey
      serviceAccountName: {{ include "onepassword-events.serviceAccountName" . }}
      volumes:
        - name: onepassword-config
          configMap:
            name: onepassword-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: onepassword-config
              mountPath: /onepassword.yaml
              subPath: onepassword.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
